spring:
  datasource:
    url: jdbc:mysql://chatserver-mysql:3306/ChatServerDB?createDatabaseIfNotExist=true
    username: root
    #    Can use Jasypt to encrypt password
    password: root

  jpa:
    show-sql: true
    #    Tells Hibernate to generate SQL requests as exactly as specified in the @Table(name=" ") or @Column(name=" ")
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    change-log: classpath:/db/changelog/liquibase-changeLog.xml